### ISSUE TITLE
Bold im Text

### ISSUE THREAD

**Issue by signalwerk** [logrinto/IAD2017.schriftmuster#54]
@larsmaeder @marc-hatt @tioemayer @matthiasmeierkoch bei der Detailseite von Open Sans (https://logrinto.github.io/IAD2017.schriftmuster/fonts/opensans/index.html) gibt es Bold im Text. Ist das OK so? Gebt doch sonst @natasharuf bescheid

**Comment by matthiasmeierkoch** [comment]
Meiner Meinung nach spricht nichts gegen Bold im Text um einzelne Wörter hervorzuheben wenn es Sinn macht. In diesem spezifischen Fall finde ich es jedoch unpassend da es wie ein Titel wirkt und sich diese Detailseite von den anderen ab hebt. 
Was meint der rest des Teams?
(kann man so machen) 👍 oder (eher nicht) 👎

**Comment by natasharuf** [comment]
Habe sie korrigiert. 

ein andere Problem habe ich noch. Ich habe alles versucht, alle Schriftschnitte einstellen. Nur stimmt ein Light-Schriftschnitt nicht. Ich weiss nicht, warum es nicht funktioniert. Obwohl die Schriftschnitt für Light-Italic gut geklappt hat. Versteht ihr was ich meine? Ihr könnt mein Anhang unten ansehen.

<img width="1352" alt="bildschirmfoto 2018-07-05 um 19 13 11" src="https://user-images.githubusercontent.com/23706140/42337749-f8044396-8087-11e8-9641-05c8f372c0a3.png">

**Comment by larsmaeder** [comment]
@natasharuf 
Schau doch nochmals bei Google Fonts vorbei, wie die `Embed Font-` und `css`-Angaben unter `@import` sind. Ich erhalte nämlich eine abweichende url zu deiner. Sprich du steuerst in deinen `.css`-Klassen auch die falsche Schriftschnitte an. Es werden wahrscheinlich deshalb die falschen geladen.

> Light müsst nach Google 300 sein, ist aber bei dir als 100 definiert usw.

**Dein Code:**
```CSS
@import url('https://fonts.googleapis.com/css?family=Open+Sans:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext');


.customfont {
  font-family: 'Opensans', sans-serif;
}
```
**Google Fonts:**
```CSS
@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i');

.customfont {
  font-family: 'Open Sans', sans-serif;
}
```
